import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "FastWords",
  description: "Generated by create next app",
  icons: {
    icon: "/fast-word-message.png",
    shortcut: "/fast-word-message.png",
    apple: "/fast-word-message.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Karla:ital,wght@0,200..800;1,200..800&display=swap" rel="stylesheet" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
