import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "FastWords",
  description: "Generated by create next app",
  icons: {
    icon: "/fast-word-message.png",
    shortcut: "/fast-word-message.png",
    apple: "/fast-word-message.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
