services:
  postgres:
    image: postgres:15
    container_name: fastwords-db
    restart: always
    environment:
      POSTGRES_DB: fastwords_db
      POSTGRES_USER: markus_fastwords
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: admin 
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  pgdata:
