version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fastwords-db
    restart: always
    environment:
      POSTGRES_DB: fastwords_db
      POSTGRES_USER: markus_fastwords
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
