spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fastwords_db
    username: markus_fastwords
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
